# Generated by Django 3.0.1 on 2020-04-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiddleChamp', '0003_auto_20200410_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunter_den_mapping',
            name='member_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
