# Generated by Django 3.0.1 on 2020-04-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiddleChamp', '0006_auto_20200410_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddle',
            name='answer_format',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='hint',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='question',
            field=models.TextField(),
        ),
    ]
