# Generated by Django 3.0.1 on 2020-04-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiddleChamp', '0007_auto_20200422_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='riddle',
            name='audio',
            field=models.FileField(blank=True, upload_to='image/riddle/'),
        ),
    ]
