# Generated by Django 3.0.1 on 2019-12-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=500)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(default=0.0)),
                ('image', models.ImageField(upload_to='image/shop/')),
            ],
        ),
    ]
