# Generated by Django 3.0.1 on 2020-04-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_userprofile_uin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=10)),
                ('error_code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
