# Generated by Django 3.0.1 on 2020-04-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_errorcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorcode',
            old_name='error',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='errorcode',
            old_name='description',
            new_name='error_message',
        ),
        migrations.RenameField(
            model_name='errorcode',
            old_name='error_code',
            new_name='hash_code',
        ),
        migrations.AddField(
            model_name='errorcode',
            name='error_title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
