# Generated by Django 3.0.1 on 2020-04-06 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_auto_20200406_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorcode',
            old_name='error_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='errorcode',
            old_name='error_title',
            new_name='title',
        ),
    ]
