# Generated by Django 3.0.1 on 2020-04-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_auto_20200406_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorcode',
            name='Type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
