# Generated by Django 3.0.1 on 2020-03-28 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Den',
            fields=[
                ('den_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, upload_to='image/den/')),
                ('score', models.FloatField(default=0.0, editable=False)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True)),
                ('invitation_code', models.CharField(default='0', editable=False, max_length=10)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DenRiddle',
            fields=[
                ('den_riddle_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('ending_at', models.DateTimeField()),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('den', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HuntersDen.Den')),
            ],
        ),
        migrations.CreateModel(
            name='RiddleCategory',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RiddleType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Riddle',
            fields=[
                ('riddle_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('media', models.ImageField(blank=True, upload_to='image/riddle/')),
                ('question', models.CharField(max_length=1000)),
                ('answer_1', models.CharField(max_length=1000)),
                ('answer_2', models.CharField(blank=True, max_length=1000)),
                ('answer_3', models.CharField(blank=True, max_length=1000)),
                ('answer_4', models.CharField(blank=True, max_length=1000)),
                ('answer_5', models.CharField(blank=True, max_length=1000)),
                ('answer_6', models.CharField(blank=True, max_length=1000)),
                ('answer_7', models.CharField(blank=True, max_length=1000)),
                ('answer_8', models.CharField(blank=True, max_length=1000)),
                ('answer_9', models.CharField(blank=True, max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HuntersDen.RiddleCategory')),
                ('type_riddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HuntersDen.RiddleType')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('answer', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='image/response/')),
                ('score', models.FloatField(default=0.0, editable=False)),
                ('response_time', models.FloatField(default=0.0, editable=False)),
                ('den_riddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HuntersDen.DenRiddle')),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hunter',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('den', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HuntersDen.Den')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='denriddle',
            name='riddle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HuntersDen.Riddle'),
        ),
    ]
