# Generated by Django 3.0.1 on 2020-03-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuntersDen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_correct',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='response_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
