# Generated by Django 3.0.1 on 2020-03-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HuntersDen', '0006_auto_20200329_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denriddle',
            name='den',
        ),
        migrations.RemoveField(
            model_name='denriddle',
            name='riddle',
        ),
        migrations.RemoveField(
            model_name='hunter_den_mapping',
            name='den',
        ),
        migrations.RemoveField(
            model_name='hunter_den_mapping',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='response',
            name='den_riddle',
        ),
        migrations.RemoveField(
            model_name='response',
            name='hunter',
        ),
        migrations.DeleteModel(
            name='Den',
        ),
        migrations.DeleteModel(
            name='DenRiddle',
        ),
        migrations.DeleteModel(
            name='Hunter_Den_Mapping',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
