# Generated by Django 3.0.1 on 2020-03-29 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HuntersDen', '0007_auto_20200329_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Den',
            fields=[
                ('den_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, upload_to='image/den/')),
                ('score', models.FloatField(default=0.0, editable=False)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('invitation_code', models.CharField(blank=True, editable=False, max_length=10)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DenRiddle',
            fields=[
                ('den_riddle_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('ending_at', models.DateTimeField()),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('den', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HuntersDen.Den')),
                ('riddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HuntersDen.Riddle')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('answer', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='image/response/')),
                ('is_correct', models.BooleanField(blank=True, default=False)),
                ('score', models.FloatField(default=0.0, editable=False)),
                ('response_at', models.DateTimeField(auto_now=True)),
                ('response_time', models.FloatField(default=0.0, editable=False)),
                ('den_riddle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HuntersDen.DenRiddle')),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hunter_Den_Mapping',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('den', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HuntersDen.Den')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
