# Generated by Django 3.0.1 on 2020-03-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuntersDen', '0008_den_denriddle_hunter_den_mapping_response'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hunter_den_mapping',
            constraint=models.UniqueConstraint(fields=('participant', 'den'), name='hunter-den'),
        ),
    ]
