# Generated by Django 3.0.1 on 2020-03-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuntersDen', '0010_auto_20200329_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiddleLevel',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('short_name', models.TextField(max_length=10)),
                ('desc', models.TextField(max_length=100)),
                ('positive_score_percent', models.FloatField(default=1.0, editable=False)),
                ('negetive_score_percent', models.FloatField(default=0.1, editable=False)),
            ],
        ),
    ]
