# Generated by Django 3.0.1 on 2020-03-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuntersDen', '0015_auto_20200329_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='den',
            name='uin_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='riddle',
            name='answer_format',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='riddle',
            name='hint',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='riddle',
            name='uin_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='response',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='answer_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='answer_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='answer_4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='answer_5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='answer_6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='answer_7',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='answer_8',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='riddle',
            name='answer_9',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
