# Generated by Django 3.0.1 on 2020-03-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuntersDen', '0016_auto_20200330_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='den',
            name='next_riddle_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
