# Generated by Django 3.0.1 on 2020-03-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuntersDen', '0021_auto_20200330_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='riddle',
            name='point',
            field=models.FloatField(blank=True, default=100),
        ),
    ]
