# Generated by Django 3.0.1 on 2020-03-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuntersDen', '0025_auto_20200331_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='denriddle',
            name='has_expired',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='denriddle',
            name='is_pending',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='denriddle',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
