# Generated by Django 3.0.1 on 2020-03-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuntersDen', '0026_auto_20200331_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='den',
            name='riddle_start_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='den',
            name='riddles_per_day',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AddField(
            model_name='den',
            name='time_bw_riddle',
            field=models.IntegerField(blank=True, default=6),
        ),
        migrations.AddField(
            model_name='denriddle',
            name='added_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
