# Generated by Django 3.0.1 on 2020-04-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuntersDen', '0032_auto_20200403_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunter_den_mapping',
            name='member_status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
