# Generated by Django 3.0.1 on 2020-04-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuntersDen', '0033_hunter_den_mapping_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='riddlelevel',
            name='time',
            field=models.IntegerField(default=30),
        ),
    ]
