# Generated by Django 3.0.1 on 2020-04-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuntersDen', '0034_riddlelevel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunter_den_mapping',
            name='invitation_code',
            field=models.CharField(blank=True, default='NR', max_length=50, null=True),
        ),
    ]
