# Generated by Django 3.0.1 on 2020-04-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuntersDen', '0035_hunter_den_mapping_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunter_den_mapping',
            name='invitation_code',
            field=models.CharField(blank=True, default='NR', max_length=100, null=True),
        ),
    ]
