# Generated by Django 3.0.1 on 2020-03-29 18:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HuntersDen', '0002_auto_20200328_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hunter',
            new_name='Hunter_Den_Mapping',
        ),
    ]
