# Generated by Django 3.0.1 on 2020-03-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuntersDen', '0009_auto_20200329_1856'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hunter_den_mapping',
            name='hunter-den',
        ),
        migrations.AddConstraint(
            model_name='hunter_den_mapping',
            constraint=models.UniqueConstraint(fields=('participant', 'den'), name='hunter_den'),
        ),
    ]
