# Generated by Django 3.0.1 on 2020-03-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuntersDen', '0011_riddlelevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddlelevel',
            name='short_name',
            field=models.CharField(max_length=10),
        ),
    ]
