# Generated by Django 3.0.1 on 2020-03-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuntersDen', '0014_riddle_riddle_level'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='denriddle',
            constraint=models.UniqueConstraint(fields=('den', 'riddle'), name='den_riddle_conposite'),
        ),
    ]
