# Generated by Django 3.0.1 on 2020-03-30 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HuntersDen', '0018_auto_20200330_2251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hunter_Den_Mapping',
        ),
    ]
