# Generated by Django 3.0.1 on 2020-03-30 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HuntersDen', '0019_delete_hunter_den_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hunter_Den_Mapping',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('den', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HuntersDen.Den')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='hunter_den_mapping',
            constraint=models.UniqueConstraint(fields=('participant', 'den'), name='hunter_den'),
        ),
    ]
