# Generated by Django 3.0.1 on 2020-03-30 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_userprofile_uin_code'),
        ('HuntersDen', '0020_auto_20200330_2258'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hunter_den_mapping',
            name='hunter_den',
        ),
        migrations.RemoveField(
            model_name='hunter_den_mapping',
            name='participant',
        ),
        migrations.AddField(
            model_name='hunter_den_mapping',
            name='hunter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Account.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='hunter_den_mapping',
            constraint=models.UniqueConstraint(fields=('hunter', 'den'), name='hunter_den'),
        ),
    ]
