# Generated by Django 3.0.1 on 2020-03-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HuntersDen', '0023_auto_20200331_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denriddle',
            name='started_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
