# Generated by Django 3.0.1 on 2020-01-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_status',
            name='remark',
            field=models.TextField(default='We will contact you via mail'),
        ),
    ]
